### ISSUE TITLE
SIGSEV invalid memory reference when running tests

### ISSUE THREAD

**Issue by jordalgo** [jjyr/buddy-alloc#16]
`cargo test` works just fine but if you run them with the release flag e.g. `cargo test --release` then you get this error:
```
$ cargo test --release
    Finished release [optimized] target(s) in 0.97s
     Running unittests src/lib.rs (target/release/deps/buddy_alloc-4e79e413804880df)

running 16 tests
test tests::buddy_alloc::test_alignment ... ok
test tests::buddy_alloc::test_basic_malloc ... ok
test tests::buddy_alloc::test_available_bytes ... ok
test tests::buddy_alloc::test_example_bug ... ok
test tests::buddy_alloc::test_fail_malloc ... ok
test tests::buddy_alloc::test_malloc_and_free ... ok
test tests::buddy_alloc::test_multiple_malloc ... ok
test tests::buddy_alloc::test_free_bug ... ok
test tests::buddy_alloc::test_small_size_malloc ... ok
test tests::fast_alloc::test_fail_malloc ... ok
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/media/psf/repos/buddy-alloc/target/release/deps/buddy_alloc-4e79e413804880df` (signal: 11, SIGSEGV: invalid memory reference)

```

**Comment by arighi** [comment]
I'm using this crate in https://github.com/sched-ext/scx/tree/main/scheds/rust/scx_rustland and it'd be really nice if we could fix these test failures.

I've investigated a bit and it seems that we can easily fix the test failures for BuddyAlloc using a memory arena buffer aligned to BLOCK_SIZE (or even page size, just to be safe). For example:
```
diff --git a/src/tests/buddy_alloc.rs b/src/tests/buddy_alloc.rs
index 309e6d5..4c6ba7c 100644
--- a/src/tests/buddy_alloc.rs
+++ b/src/tests/buddy_alloc.rs
@@ -223,12 +223,15 @@ fn test_example_bug() {
     });
 }

+#[repr(align(4096))]
+struct AlignedData([u8; 4 << 16]);
+
 #[test]
 fn test_alignment() {
-    let data = [0u8; 4 << 16];
-    println!("Buffer data: {:p}", data.as_ptr());
+    let data = AlignedData([0u8; 4 << 16]);
+    println!("Buffer data: {:p}", data.0.as_ptr());
     let mut allocator =
-        unsafe { BuddyAlloc::new(BuddyAllocParam::new(data.as_ptr(), 4 << 16, 4096)) };
+        unsafe { BuddyAlloc::new(BuddyAllocParam::new(data.0.as_ptr(), 4 << 16, 4096)) };
     let p = allocator.malloc(4);
     println!("Allocated pointer: {:p}", p);
 }
```

However, many tests in FastAlloc can't be fixed easily (or at least I haven't found a trivial fix) and aligning the buffer doesn't seem enough. I'm a bit worried that the FastAlloc may actually have issues when it's compiled in release mode, so for now I'm planning to change my code to use only BuddyAlloc for all allocations, including the code directly in my project (adding a reference to this project of course and updating the licensing info), so that we can package everything easily without having to hint or workaround the failed tests for the buddy-alloc crate.

Please, let me know if you have any objection or concern with this.

As soon as these issues are fixed / addressed I'll re-add the create as a proper dependency.

**Comment by jjyr** [comment]
Thanks for the detailed bug report! In my opinion, it is the right choice to use only BuddyAlloc. Feel free to copy the code since it is MIT licensed :)

I will look into the FastAlloc issue once I have time. It may take more time to address it, I have no clue for now.

**Comment by jjyr** [comment]
For short, it is a bug in the fast alloc test. I will send a PR to fix it and release a new version.

---------------------

Some update:

I have found the testcase causes the invalid memory access:

``` sh
cargo test --release fast_alloc::test_multiple_malloc
```
I try to use random build options to run the test, try to find which option causes the test fail. 

And finally, I found these three

``` toml
# Fail
[profile.dev]
opt-level = 3
debug-assertions = false
overflow-checks = false
```

Run tests with these build options will produce the same failure.

``` sh
cargo test --profile dev fast_alloc::test_multiple_malloc
```

After few tries. I find with `opt-level=0`, this test will success, it seem like `opt-level=1` introduces some optimization to cause the fail.

``` toml
# Success
[profile.dev]
opt-level = 0
debug-assertions = false
overflow-checks = false
```

But what I can't explained is when using `opt-level=1` but remove the other build options the test will success.

``` toml
# Success
[profile.dev]
opt-level = 1

# Fail
[profile.dev]
opt-level = 1
debug-assertions = false
```

It looks like some dark coner of rustc, I decided not to dig into this further.

**Comment by decathorpe** [comment]
> It looks like some dark coner of rustc

yup, but that dark corner increasingly looks like undefined behaviour 👻

**Comment by jjyr** [comment]
https://github.com/jjyr/buddy-alloc/blob/1a3e2e20234c3c2068dd5440c26339dd6cb6ab9c/src/fast_alloc.rs#L44-L45

After a hint from ChatGPT, I'm almost certain that the issue is due to the compiler ignoring pointer aliasing, which caused line 44 to be discarded.
